// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BLSystem.Models
{
    [Table("Fag")]
    public partial class Fag
    {
        [Key]
        [Column("Fag_id")]
        public int FagId { get; set; }
        [Required]
        [Column("Fag_navn")]
        [StringLength(50)]
        public string FagNavn { get; set; }
    }
}