// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BLSystem.Models
{
    [Table("Hold")]
    public partial class Hold
    {
        public Hold()
        {
            BogHolds = new HashSet<BogHold>();
            UnderviserHolds = new HashSet<UnderviserHold>();
        }

        [Key]
        [Column("Hold_id")]
        public int Hold_Id { get; set; }

        [InverseProperty(nameof(BogHold.Hold))]
        public virtual ICollection<BogHold> BogHolds { get; set; }
        [InverseProperty(nameof(UnderviserHold.Hold))]
        public virtual ICollection<UnderviserHold> UnderviserHolds { get; set; }
    }
}