// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BLSystem.Models
{
    [Table("Semestre")]
    public partial class Semestre
    {
        [Key]
        [Column("Semestre_id")]
        public int SemestreId { get; set; }
        [Required]
        [StringLength(50)]
        public string Navn { get; set; }
    }
}