// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BLSystem.Models
{
    [Table("Underviser")]
    public partial class Underviser
    {
        public Underviser()
        {
            UnderviserBogs = new HashSet<UnderviserBog>();
            UnderviserHolds = new HashSet<UnderviserHold>();
        }

        [Key]
        [Column("Underviser_id")]
        public int Underviser_Id { get; set; }
        [Required]
        [StringLength(30)]
        public string Navn { get; set; }
        [Required]
        [StringLength(10)]
        public string Initialer { get; set; }

        [InverseProperty(nameof(UnderviserBog.Underviser))]
        public virtual ICollection<UnderviserBog> UnderviserBogs { get; set; }
        [InverseProperty(nameof(UnderviserHold.Underviser))]
        public virtual ICollection<UnderviserHold> UnderviserHolds { get; set; }
    }
}