// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BLSystem.Models
{
    [Table("UnderviserBog")]
    public partial class UnderviserBog
    {
        [Key]
        [Column("UnderviserBog_id")]
        public int UnderviserBogId { get; set; }
        [Column("Underviser_id")]
        public int UnderviserId { get; set; }
        [Column("Bog_id")]
        public int BogId { get; set; }

        [ForeignKey(nameof(BogId))]
        [InverseProperty("UnderviserBogs")]
        public virtual Bog Bog { get; set; }
        [ForeignKey(nameof(UnderviserId))]
        [InverseProperty("UnderviserBogs")]
        public virtual Underviser Underviser { get; set; }
    }
}